server {
    listen 80 default_server;
    listen [::]:80 default_server;
    # also listen on 7860 to satisfy platforms expecting that port
    listen 7860;
    listen [::]:7860;
    server_name _;

    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
}
